travis:
  secure:
    BINSTAR_TOKEN: DFiSDMRRa8BNZtEfLu0idgrIuTDCSA7hmk591OQTzz5zok0toTxtNmS3ob/ycsrAOCaC79yaA7TbEiMM1mqTPe7BdCGB5dkTTNg2U2jIj7mcZTB5AQMOzYkvsF5+8b25MwiZUL5ftDaB7cOsNFIaTF72WMRC8+SpDArG7jkqKArbT1SRYl3Uu7hn4kkAGiWmMEaJ7C8vm4s1vnIgPWAOG7W8pL7YKZ76c2b8Ebz3BcAmo1PymuQ3eaZ4kcn5VngGfh2alh/mE7I2SgmPZZ1xzf9jiyCTLAoP8oCQ40ClYSVtT1u9KPVE+emp8PQ1Uda4bF8dmiC9yz8ISvUDJs8xsGh6+I7IXoF2v5aw68YV2kIkMffHIpvL/+a01Uyr2WywPm1bU/SZlAEBJR6QyMQIVpWql60/L9iZbpc/MXtk/pb+vakq6P7EqDW7GHlE0EsZVsGZdFU27hkQmdLpJEIa7NUoip/3QY3pd2H64RRxFlK1z3iyVTd/ejSNs0II2JGN0d/0DtIC8mBtOOFlIN7jHsvxNUbsngBODcw2/YKWzXahVv/ih5aKEPATJFjsBxNwlfbKi3hNPrCdiQK1ymAgPEP8s/ZjAcJeDXAN/7fGU6ZL9cHi/+Pk4BPeDFsMvmchniT5X/Zup9crHPsWmfxFJew/LfsUUtn6uWYaNxeZPN0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
